"""add_agent_id_to_api_keys_and_traces

Revision ID: 8b896ecd5881
Revises: 92b3ce2809d4
Create Date: 2026-04-14 21:28:13.070843

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '8b896ecd5881'
down_revision = '92b3ce2809d4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('agent_id', sa.String(length=100), nullable=True))
    op.add_column('traces', sa.Column('agent_id', sa.String(length=100), nullable=True))
    op.add_column('traces', sa.Column('agent_config_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('traces', 'agent_config_id')
    op.drop_column('traces', 'agent_id')
    op.add_column('knowledge_embeddings', sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True))
    op.drop_column('api_keys', 'agent_id')
    # ### end Alembic commands ###