"""add_agent_configs_table_and_memory_agent_id

Revision ID: 92b3ce2809d4
Revises: b0b4a3861c4d
Create Date: 2026-04-14 20:49:03.508408

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '92b3ce2809d4'
down_revision = 'b0b4a3861c4d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('agent_id', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('system_prompt_additions', sa.Text(), nullable=True),
    sa.Column('escalation_contact', sa.String(length=200), nullable=True),
    sa.Column('allowed_domains', sa.JSON(), nullable=True),
    sa.Column('policy_overrides', sa.JSON(), nullable=True),
    sa.Column('preferred_provider', sa.String(length=50), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'agent_id', name='uq_tenant_agent')
    )
    op.create_index(op.f('ix_agent_configs_agent_id'), 'agent_configs', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_configs_tenant_id'), 'agent_configs', ['tenant_id'], unique=False)
    op.add_column('memory_items', sa.Column('agent_id', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_memory_items_agent_id'), 'memory_items', ['agent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_memory_items_agent_id'), table_name='memory_items')
    op.drop_column('memory_items', 'agent_id')
    op.add_column('knowledge_embeddings', sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_agent_configs_tenant_id'), table_name='agent_configs')
    op.drop_index(op.f('ix_agent_configs_agent_id'), table_name='agent_configs')
    op.drop_table('agent_configs')
    # ### end Alembic commands ###