"""add memory_items table

Revision ID: ae3866cd9adc
Revises: 17ab56bdd913
Create Date: 2026-04-11 08:01:07.022868

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'ae3866cd9adc'
down_revision = '17ab56bdd913'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memory_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source_session_id', sa.String(length=36), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_items_tenant_id'), 'memory_items', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_memory_items_user_id'), 'memory_items', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_memory_items_user_id'), table_name='memory_items')
    op.drop_index(op.f('ix_memory_items_tenant_id'), table_name='memory_items')
    op.drop_table('memory_items')
    # ### end Alembic commands ###