"""add knowledge_embeddings table

Revision ID: b0e003ffa07f
Revises: 7fb73e7eb812
Create Date: 2026-04-12 19:21:34.170367

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'b0e003ffa07f'
down_revision = '7fb73e7eb812'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_embeddings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=True),
    sa.Column('domain_id', sa.String(length=100), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('knowledge_type', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # Enable pgvector extension
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # Add the embedding vector column (1536 dimensions for OpenAI embeddings)
    op.execute(
        "ALTER TABLE knowledge_embeddings ADD COLUMN embedding vector(1536)"
    )

    # Create an index for fast similarity search
    op.execute(
        "CREATE INDEX ix_knowledge_embedding_vector "
        "ON knowledge_embeddings USING ivfflat (embedding vector_cosine_ops) "
        "WITH (lists = 100)"
    )
    op.create_index(op.f('ix_knowledge_embeddings_domain_id'), 'knowledge_embeddings', ['domain_id'], unique=False)
    op.create_index(op.f('ix_knowledge_embeddings_tenant_id'), 'knowledge_embeddings', ['tenant_id'], unique=False)
    op.create_index('ix_knowledge_scope', 'knowledge_embeddings', ['tenant_id', 'domain_id', 'knowledge_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_knowledge_scope', table_name='knowledge_embeddings')
    op.drop_index(op.f('ix_knowledge_embeddings_tenant_id'), table_name='knowledge_embeddings')
    op.drop_index(op.f('ix_knowledge_embeddings_domain_id'), table_name='knowledge_embeddings')
    op.drop_table('knowledge_embeddings')
    # ### end Alembic commands ###

    op.execute("DROP INDEX IF EXISTS ix_knowledge_embedding_vector")
    op.execute("ALTER TABLE knowledge_embeddings DROP COLUMN IF EXISTS embedding")