"""update retention tables and add missing columns

Revision ID: e66b99460b68
Revises: a9860a389484
Create Date: 2026-04-16 11:35:16.056394

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'e66b99460b68'
down_revision = 'a9860a389484'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deletion_logs', sa.Column('rows_affected', sa.Integer(), nullable=False))
    op.add_column('deletion_logs', sa.Column('cutoff_date', sa.String(length=30), nullable=False))
    op.drop_column('deletion_logs', 'records_affected')
    op.drop_column('deletion_logs', 'retention_days_applied')
    op.add_column('retention_policies', sa.Column('active', sa.Boolean(), nullable=False))
    op.add_column('retention_policies', sa.Column('created_by', sa.String(length=100), nullable=True))
    op.add_column('retention_policies', sa.Column('updated_by', sa.String(length=100), nullable=True))
    op.alter_column('retention_policies', 'purpose',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('retention_policies', 'purpose',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('retention_policies', 'updated_by')
    op.drop_column('retention_policies', 'created_by')
    op.drop_column('retention_policies', 'active')
    op.add_column('deletion_logs', sa.Column('retention_days_applied', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('deletion_logs', sa.Column('records_affected', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('deletion_logs', 'cutoff_date')
    op.drop_column('deletion_logs', 'rows_affected')
    # ### end Alembic commands ###