"""add_user_consents_table

Revision ID: 107ed978475b
Revises: 8f88dbaf4ee7
Create Date: 2026-04-16 17:07:37.629934

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '107ed978475b'
down_revision = '8f88dbaf4ee7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###