"""admin_audit_logs.tenant_id nullable for platform-level actions

Revision ID: 4d9c21f3e8a7
Revises: 3447ac8b45b4
Create Date: 2026-04-22 23:30:00.000000

Step 27a: Drop NOT NULL constraint on admin_audit_logs.tenant_id.

Rationale: platform-level admin actions (platform-admin key rotation,
cross-tenant deactivation, async worker lifecycle events in Step 27b,
etc.) have no tenant scope by definition. Forcing a tenant_id on those
audit rows either (a) lies in the audit trail by picking an arbitrary
tenant, destroying forensic value, or (b) blocks the action entirely.

Same shape as 26b.1's `3447ac8b45b4` fix on `api_keys.tenant_id`.
Invariant 5 compliance: scope arithmetic only — platform-admin bypass
is determined by the platform_admin permission, not by scoping.

Discovered during Step 27a File 1.1 execution when the rotation script
failed with NotNullViolation trying to write a tenant_id=NULL audit row
for a platform-level key rotation.

Hand-written per Invariant 12. Not autogenerated.

Verification:
  - alembic upgrade head clean: 3447ac8b45b4 -> 4d9c21f3e8a7
  - DB column check: admin_audit_logs.tenant_id nullable=True, VARCHAR(100)
  - app.main imports clean
  - 10-pillar verification suite 10/10 green post-migration

Downgrade caveat: if any admin_audit_logs rows have tenant_id=NULL at
downgrade time, the reverse alter_column will fail. This is correct
behavior — those rows represent legitimate platform-level actions that
cannot be retroactively attributed to a tenant. Operator would need to
backfill or delete them before downgrading.

This is an additive, non-destructive DDL change with no data movement.
Safe to apply to prod RDS currently at 3447ac8b45b4. Will be applied
via the same one-shot ECS Fargate task pattern used in Step 26b
Phase 5b at Step 27b deploy time.
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4d9c21f3e8a7"
down_revision = "3447ac8b45b4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.alter_column(
        "admin_audit_logs",
        "tenant_id",
        existing_type=sa.String(length=100),
        nullable=True,
    )


def downgrade() -> None:
    # Fails if any NULL rows exist at downgrade time — see module docstring.
    op.alter_column(
        "admin_audit_logs",
        "tenant_id",
        existing_type=sa.String(length=100),
        nullable=False,
    )