"""add tenant_configs and domain_configs tables and update traces

Revision ID: 7fb73e7eb812
Revises: d7f2ad643640
Create Date: 2026-04-12 19:07:20.371159

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '7fb73e7eb812'
down_revision = 'd7f2ad643640'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domain_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('domain_id', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('system_prompt_additions', sa.Text(), nullable=True),
    sa.Column('allowed_tools', sa.JSON(), nullable=True),
    sa.Column('escalation_contact', sa.String(length=200), nullable=True),
    sa.Column('policy_overrides', sa.JSON(), nullable=True),
    sa.Column('preferred_provider', sa.String(length=50), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'domain_id', name='uq_tenant_domain')
    )
    op.create_index(op.f('ix_domain_configs_domain_id'), 'domain_configs', ['domain_id'], unique=False)
    op.create_index(op.f('ix_domain_configs_tenant_id'), 'domain_configs', ['tenant_id'], unique=False)
    op.create_table('tenant_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('escalation_contact', sa.String(length=200), nullable=True),
    sa.Column('allowed_domains', sa.JSON(), nullable=True),
    sa.Column('system_prompt_additions', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_configs_tenant_id'), 'tenant_configs', ['tenant_id'], unique=True)
    op.add_column('traces', sa.Column('domain_id', sa.String(length=100), nullable=True))
    op.add_column('traces', sa.Column('memories_used', sa.JSON(), nullable=True))
    op.add_column('traces', sa.Column('tenant_config_id', sa.Integer(), nullable=True))
    op.add_column('traces', sa.Column('domain_config_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('traces', 'domain_config_id')
    op.drop_column('traces', 'tenant_config_id')
    op.drop_column('traces', 'memories_used')
    op.drop_column('traces', 'domain_id')
    op.drop_index(op.f('ix_tenant_configs_tenant_id'), table_name='tenant_configs')
    op.drop_table('tenant_configs')
    op.drop_index(op.f('ix_domain_configs_tenant_id'), table_name='domain_configs')
    op.drop_index(op.f('ix_domain_configs_domain_id'), table_name='domain_configs')
    op.drop_table('domain_configs')
    # ### end Alembic commands ###