"""add retention_policies and deletion_logs

Revision ID: a9860a389484
Revises: 8b896ecd5881
Create Date: 2026-04-16 11:26:49.358516

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'a9860a389484'
down_revision = '8b896ecd5881'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deletion_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=True),
    sa.Column('data_category', sa.String(length=50), nullable=False),
    sa.Column('action_taken', sa.String(length=20), nullable=False),
    sa.Column('records_affected', sa.Integer(), nullable=False),
    sa.Column('retention_days_applied', sa.Integer(), nullable=False),
    sa.Column('triggered_by', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deletion_logs_tenant_id'), 'deletion_logs', ['tenant_id'], unique=False)
    op.create_table('retention_policies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=True),
    sa.Column('data_category', sa.String(length=50), nullable=False),
    sa.Column('retention_days', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'data_category', name='uq_retention_tenant_category')
    )
    op.create_index(op.f('ix_retention_policies_tenant_id'), 'retention_policies', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_embeddings', sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_retention_policies_tenant_id'), table_name='retention_policies')
    op.drop_table('retention_policies')
    op.drop_index(op.f('ix_deletion_logs_tenant_id'), table_name='deletion_logs')
    op.drop_table('deletion_logs')
    # ### end Alembic commands ###