"""Arc 16 (c) — knowledge graph store: nodes + edges + RLS.

Creates the graph knowledge store (Architecture §3.2.1, Locked
Decisions 4–6; Vision §3.3). PostgreSQL-native — no new vendor. Tables:

  * ``knowledge_graph_nodes`` — typed, domain-agnostic entities
    (entity_type / entity_label / attributes JSONB) extracted from
    ingested knowledge, with a source_id provenance back-reference.
  * ``knowledge_graph_edges`` — directed, typed relationships between
    nodes (src→dst, relationship_type), also source-attributed.

Hand-written (NOT autogenerated): the knowledge_chunks model carries an
out-of-band pgvector column that autogenerate would try to "add", and
RLS policies are not autogenerate-visible. This migration is authored
end-to-end so the RLS posture is explicit and correct from birth.

RLS posture (matches the corrected pattern from arc16_a/arc16_b, both
isolation walls):
  * FORCE ROW LEVEL SECURITY (owner is subject too).
  * RESTRICTIVE tenant fence: admin_id = app.admin_id (Wall 1, the
    absolute boundary — "Across Admins: never").
  * RESTRICTIVE instance fence: luciel_instance_id = app.instance_id
    (Wall 3).
  * PERMISSIVE base-grant with the same predicates (without at least
    one PERMISSIVE policy the table is deny-all — the bug arc16_b
    fixed; these tables are born with it correct).

These tables are born strict-tenant: no admin_id-IS-NULL cross-tenant
carve-out ever exists here.

Refs: app/models/knowledge_graph.py, arc16_a (strict-tenant pattern),
arc16_b (RESTRICTIVE+PERMISSIVE pairing), Architecture §3.2.1 / §3.7.
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision = "arc16_c_knowledge_graph_store"
down_revision = "arc16_b_knowledge_sources_permissive_fix"
branch_labels = None
depends_on = None


_NODES = "knowledge_graph_nodes"
_EDGES = "knowledge_graph_edges"


def _install_rls(table: str) -> None:
    """RESTRICTIVE tenant+instance fences + PERMISSIVE base-grant."""
    op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY;")
    op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY;")

    # PERMISSIVE base-grant (required so the AND of RESTRICTIVE policies
    # has something to grant on — otherwise deny-all).
    op.execute(
        f"""
        CREATE POLICY {table}_tenant_permissive
            ON {table}
            AS PERMISSIVE
            FOR ALL
            USING (
                (admin_id)::text = current_setting('app.admin_id', true)
            )
            WITH CHECK (
                (admin_id)::text = current_setting('app.admin_id', true)
            );
        """
    )
    # RESTRICTIVE tenant fence (Wall 1, absolute).
    op.execute(
        f"""
        CREATE POLICY {table}_tenant_isolation
            ON {table}
            AS RESTRICTIVE
            FOR ALL
            USING (
                (admin_id)::text = current_setting('app.admin_id', true)
            )
            WITH CHECK (
                (admin_id)::text = current_setting('app.admin_id', true)
            );
        """
    )
    # RESTRICTIVE instance fence (Wall 3).
    op.execute(
        f"""
        CREATE POLICY {table}_instance_isolation
            ON {table}
            AS RESTRICTIVE
            FOR ALL
            USING (
                (luciel_instance_id)::text
                    = current_setting('app.instance_id', true)
            )
            WITH CHECK (
                (luciel_instance_id)::text
                    = current_setting('app.instance_id', true)
            );
        """
    )


def upgrade() -> None:
    # ---- nodes ----
    op.create_table(
        _NODES,
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column(
            "admin_id",
            sa.String(length=100),
            sa.ForeignKey("admins.id", ondelete="RESTRICT"),
            nullable=False,
        ),
        sa.Column(
            "luciel_instance_id",
            sa.Integer(),
            sa.ForeignKey(
                "instances.id",
                ondelete="SET NULL",
                name="fk_knowledge_graph_nodes_luciel_instance_id",
            ),
            nullable=False,
        ),
        sa.Column("entity_type", sa.String(length=120), nullable=False),
        sa.Column("entity_label", sa.String(length=500), nullable=False),
        sa.Column("attributes", postgresql.JSONB(), nullable=True),
        sa.Column(
            "source_id",
            sa.BigInteger(),
            sa.ForeignKey(
                "knowledge_sources.id",
                ondelete="CASCADE",
                name="fk_knowledge_graph_nodes_source_id",
            ),
            nullable=False,
        ),
        sa.Column("superseded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("soft_deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.UniqueConstraint(
            "admin_id",
            "luciel_instance_id",
            "entity_type",
            "entity_label",
            name="uq_knowledge_graph_nodes_resolution",
        ),
    )
    op.create_index(
        "ix_knowledge_graph_nodes_admin_id", _NODES, ["admin_id"]
    )
    op.create_index(
        "ix_knowledge_graph_nodes_luciel_instance_id",
        _NODES,
        ["luciel_instance_id"],
    )
    op.create_index(
        "ix_knowledge_graph_nodes_source_id", _NODES, ["source_id"]
    )
    op.create_index(
        "ix_knowledge_graph_nodes_scope_type",
        _NODES,
        ["admin_id", "luciel_instance_id", "entity_type"],
    )

    # ---- edges ----
    op.create_table(
        _EDGES,
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column(
            "admin_id",
            sa.String(length=100),
            sa.ForeignKey("admins.id", ondelete="RESTRICT"),
            nullable=False,
        ),
        sa.Column(
            "luciel_instance_id",
            sa.Integer(),
            sa.ForeignKey(
                "instances.id",
                ondelete="SET NULL",
                name="fk_knowledge_graph_edges_luciel_instance_id",
            ),
            nullable=False,
        ),
        sa.Column(
            "src_node_id",
            sa.BigInteger(),
            sa.ForeignKey(
                "knowledge_graph_nodes.id",
                ondelete="CASCADE",
                name="fk_knowledge_graph_edges_src_node_id",
            ),
            nullable=False,
        ),
        sa.Column(
            "dst_node_id",
            sa.BigInteger(),
            sa.ForeignKey(
                "knowledge_graph_nodes.id",
                ondelete="CASCADE",
                name="fk_knowledge_graph_edges_dst_node_id",
            ),
            nullable=False,
        ),
        sa.Column("relationship_type", sa.String(length=120), nullable=False),
        sa.Column(
            "source_id",
            sa.BigInteger(),
            sa.ForeignKey(
                "knowledge_sources.id",
                ondelete="CASCADE",
                name="fk_knowledge_graph_edges_source_id",
            ),
            nullable=False,
        ),
        sa.Column("superseded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("soft_deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.UniqueConstraint(
            "admin_id",
            "luciel_instance_id",
            "src_node_id",
            "dst_node_id",
            "relationship_type",
            name="uq_knowledge_graph_edges_triple",
        ),
    )
    op.create_index(
        "ix_knowledge_graph_edges_admin_id", _EDGES, ["admin_id"]
    )
    op.create_index(
        "ix_knowledge_graph_edges_luciel_instance_id",
        _EDGES,
        ["luciel_instance_id"],
    )
    op.create_index(
        "ix_knowledge_graph_edges_src_node_id", _EDGES, ["src_node_id"]
    )
    op.create_index(
        "ix_knowledge_graph_edges_dst_node_id", _EDGES, ["dst_node_id"]
    )
    op.create_index(
        "ix_knowledge_graph_edges_source_id", _EDGES, ["source_id"]
    )
    op.create_index(
        "ix_knowledge_graph_edges_traverse_src",
        _EDGES,
        ["admin_id", "luciel_instance_id", "src_node_id", "relationship_type"],
    )
    op.create_index(
        "ix_knowledge_graph_edges_traverse_dst",
        _EDGES,
        ["admin_id", "luciel_instance_id", "dst_node_id", "relationship_type"],
    )

    # ---- RLS on both, from birth ----
    _install_rls(_NODES)
    _install_rls(_EDGES)


def downgrade() -> None:
    # Drop edges first (FK to nodes). Policies drop with the table.
    op.drop_table(_EDGES)
    op.drop_table(_NODES)
