"""add_agent_config_and_agent_id_columns

Revision ID: b0b4a3861c4d
Revises: edb185277456
Create Date: 2026-04-14 19:50:13.553585

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'b0b4a3861c4d'
down_revision = 'edb185277456'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_embeddings', sa.Column('agent_id', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_knowledge_embeddings_agent_id'), 'knowledge_embeddings', ['agent_id'], unique=False)
    op.drop_column('knowledge_embeddings', 'embedding')
    op.add_column('sessions', sa.Column('agent_id', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_sessions_agent_id'), 'sessions', ['agent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessions_agent_id'), table_name='sessions')
    op.drop_column('sessions', 'agent_id')
    op.add_column('knowledge_embeddings', sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_knowledge_embeddings_agent_id'), table_name='knowledge_embeddings')
    op.drop_column('knowledge_embeddings', 'agent_id')
    # ### end Alembic commands ###