"""add traces table

Revision ID: d7f2ad643640
Revises: ae3866cd9adc
Create Date: 2026-04-11 10:55:19.097712

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'd7f2ad643640'
down_revision = 'ae3866cd9adc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('traces',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trace_id', sa.String(length=100), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('user_message', sa.Text(), nullable=False),
    sa.Column('assistant_reply', sa.Text(), nullable=False),
    sa.Column('llm_provider', sa.String(length=50), nullable=True),
    sa.Column('llm_model', sa.String(length=100), nullable=True),
    sa.Column('memories_retrieved', sa.Integer(), nullable=False),
    sa.Column('tool_called', sa.Boolean(), nullable=False),
    sa.Column('tool_name', sa.String(length=100), nullable=True),
    sa.Column('escalated', sa.Boolean(), nullable=False),
    sa.Column('policy_flags', sa.JSON(), nullable=True),
    sa.Column('memories_extracted', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_traces_session_id'), 'traces', ['session_id'], unique=False)
    op.create_index(op.f('ix_traces_trace_id'), 'traces', ['trace_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_traces_trace_id'), table_name='traces')
    op.drop_index(op.f('ix_traces_session_id'), table_name='traces')
    op.drop_table('traces')
    # ### end Alembic commands ###