# Luciel -- 7 Stripe Price ID SSM puts (Step 30a.2 GATE 2 step 2)
# Generated by scripts/stripe_create_live_prices.py at 2026-05-14T17:47:40.046173+00:00
# Region: ca-central-1
#
# Run this on your local PowerShell with luciel-admin IAM creds.
# Each command is idempotent (--overwrite); re-run safe.
#
# Cross-ref: docs/DRIFTS.md §3 D-stripe-credentials-never-wired-to-prod-backend-2026-05-14

# Individual monthly ($30 CAD)
aws ssm put-parameter `
  --name "/luciel/production/stripe_price_individual" `
  --value "price_1TX3MGRytQVRVXw7TPKQiCAS" `
  --type SecureString `
  --region ca-central-1 `
  --overwrite

# Individual annual ($300 CAD)
aws ssm put-parameter `
  --name "/luciel/production/stripe_price_individual_annual" `
  --value "price_1TX3MGRytQVRVXw7408HJhsG" `
  --type SecureString `
  --region ca-central-1 `
  --overwrite

# Team monthly ($300 CAD)
aws ssm put-parameter `
  --name "/luciel/production/stripe_price_team_monthly" `
  --value "price_1TX3MHRytQVRVXw7LazGyxZH" `
  --type SecureString `
  --region ca-central-1 `
  --overwrite

# Team annual ($3,000 CAD)
aws ssm put-parameter `
  --name "/luciel/production/stripe_price_team_annual" `
  --value "price_1TX3MHRytQVRVXw7pVbzGSX0" `
  --type SecureString `
  --region ca-central-1 `
  --overwrite

# Company monthly ($2,000 CAD)
aws ssm put-parameter `
  --name "/luciel/production/stripe_price_company_monthly" `
  --value "price_1TX3MIRytQVRVXw79cYZwjVw" `
  --type SecureString `
  --region ca-central-1 `
  --overwrite

# Company annual ($20,000 CAD)
aws ssm put-parameter `
  --name "/luciel/production/stripe_price_company_annual" `
  --value "price_1TX3MIRytQVRVXw7b7qXMaX1" `
  --type SecureString `
  --region ca-central-1 `
  --overwrite

# Intro fee ($100 CAD one-time)
aws ssm put-parameter `
  --name "/luciel/production/stripe_price_intro_fee" `
  --value "price_1TX3MJRytQVRVXw7W1ltYCab" `
  --type SecureString `
  --region ca-central-1 `
  --overwrite

# Verify all 7 puts landed:
aws ssm describe-parameters `
  --parameter-filters "Key=Name,Option=BeginsWith,Values=/luciel/production/stripe_price_" `
  --region ca-central-1
