"""ScopeAssignment model -- first-class binding of User to (tenant, domain, role).

Step 24.5b Q6 resolution: "Data lives with scope, not person. Users + scope
assignments + mandatory key rotation + immutable audit log."

A ScopeAssignment is the durable record of "User U held role R within
(tenant T, domain D) from time A to time B (or still active if B is null)."

Design contract:
- Promotion = end old assignment (set ended_at, ended_reason=PROMOTED) and
  create a new one. Two rows in history, never UPDATE in place. This makes
  role history walkable backwards for PIPEDA/audit.
- Demotion / reassignment / departure follow the same end-and-recreate or
  end-only pattern. ended_reason captures the why.
- Agent rows (legacy, retained) become a denormalized read-optimized view of
  "currently active scope assignments per (user, tenant, domain)". The source
  of truth for role is here, not in agents.
- Mandatory key rotation wired at the service layer (Commit 2): when an
  assignment is ended, all ApiKeys bound to the affected Agent and any
  LucielInstance under that Agent are deactivated in the same txn (Invariant 4)
  and an immutable audit row is emitted.

Relationships:
- ScopeAssignment N..1 User (the durable identity).
- ScopeAssignment N..1 TenantConfig (tenant scope).
- ScopeAssignment N..1 DomainConfig (domain scope).
- Agent has a navigational view-only relationship back here via multi-column
  primaryjoin (File 1.3). Agent does not own assignment lifecycle.

Invariants honored:
- Invariant 3: ended_at instead of DELETE. Rows persist forever.
- Invariant 4: assignment lifecycle changes emit audit rows in same txn
  (handled at service layer, not here).
- Invariant 5: scope arithmetic unchanged -- ScopeAssignment carries the same
  (tenant_id, domain_id) tuple that ScopePolicy already enforces against.
- Invariant 12: hand-written migration (File 1.9), not autogenerated.

End reasons (enum):
- PROMOTED   -- replaced by a higher-scope assignment under same tenant
- DEMOTED    -- replaced by a lower-scope assignment under same tenant
- REASSIGNED -- moved to a different (domain, role) within same tenant
- DEPARTED   -- left this tenant entirely (User may still hold assignments
                under other tenants)
- DEACTIVATED-- administrative action (audit row required)
"""
from __future__ import annotations

import enum
import uuid
from datetime import datetime
from typing import TYPE_CHECKING

from sqlalchemy import (
    Boolean,
    DateTime,
    Enum as SAEnum,
    ForeignKey,
    Index,
    String,
    text,
)
from sqlalchemy.dialects.postgresql import UUID as PG_UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import Base, TimestampMixin

if TYPE_CHECKING:
    from app.models.user import User


class EndReason(str, enum.Enum):
    """Why a scope assignment ended. Recorded immutably in ended_reason column."""

    PROMOTED = "PROMOTED"
    DEMOTED = "DEMOTED"
    REASSIGNED = "REASSIGNED"
    DEPARTED = "DEPARTED"
    DEACTIVATED = "DEACTIVATED"


class ScopeAssignment(Base, TimestampMixin):
    """Durable record of a User holding a role within a (tenant, domain) scope."""

    __tablename__ = "scope_assignments"

    id: Mapped[uuid.UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    )

    # The durable identity this assignment belongs to. Required.
    user_id: Mapped[uuid.UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="RESTRICT"),
        nullable=False,
        index=True,
    )

    # Tenant + domain + role triple. Mirrors the scope-arithmetic columns
    # used elsewhere (api_keys, agents, luciel_instances). String FKs match
    # existing project convention (tenant_configs.tenant_id is VARCHAR(100)).
    tenant_id: Mapped[str] = mapped_column(
        String(100),
        ForeignKey("tenant_configs.tenant_id", ondelete="RESTRICT"),
        nullable=False,
        index=True,
    )

    # domain_id is validated at the service layer against domain_configs
    # (which uses (tenant_id, domain_id) as natural key), matching the same
    # pattern Agent.domain_id uses. No direct FK to avoid composite-key
    # mismatch with existing schema convention.
    domain_id: Mapped[str] = mapped_column(
        String(100),
        nullable=False,
    )

    # Role label within the (tenant, domain) scope. Free-form string for now
    # (e.g. "listings_agent", "team_lead", "broker_of_record"). A future step
    # may promote this to an enum once we see real-world role taxonomy stabilize.
    role: Mapped[str] = mapped_column(
        String(100),
        nullable=False,
    )

    # When the assignment started. Server-default to now() so historical
    # backfills can override; new rows default to creation time.
    started_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=text("now()"),
    )

    # When the assignment ended. NULL means currently active. Set this column
    # (do not DELETE the row) when role changes. Per Invariant 3.
    ended_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )

    # Why the assignment ended. NULL while active, mandatory once ended_at is
    # set. Service-layer enforces the (ended_at IS NULL) <-> (ended_reason IS
    # NULL) invariant; DB-level partial check constraint added in File 1.9.
    ended_reason: Mapped[EndReason | None] = mapped_column(
        SAEnum(
            EndReason,
            name="scope_assignment_end_reason",
            native_enum=True,
            create_constraint=True,
            validate_strings=True,
        ),
        nullable=True,
    )

    # Free-form context for the end action. e.g. "promoted to team lead",
    # "departed REMAX Crossroads 2026-05-01". Non-PII safe; PII goes in the
    # audit log row, not here.
    ended_note: Mapped[str | None] = mapped_column(
        String(500),
        nullable=True,
    )

    # Who actioned the change. References api_keys.id of the actor key at end
    # time. NULL for system-initiated end (e.g. cascade from User deactivation).
    ended_by_api_key_id: Mapped[int | None] = mapped_column(
        ForeignKey("api_keys.id", ondelete="SET NULL"),
        nullable=True,
    )

    # Soft-delete flag in addition to ended_at. Distinguishes "ended cleanly
    # via business process" from "administratively voided". Defaults True.
    active: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        server_default=text("true"),
    )

    # ------ relationships ------
    # Lazy="select" (default) -- explicit eager loading happens at the
    # repository layer where it's needed. Avoid N+1 silently.
    user: Mapped["User"] = relationship(
        "User",
        back_populates="scope_assignments",
        foreign_keys=[user_id],
        lazy="select",
    )

    # ------ table-level indexes / constraints ------
    __table_args__ = (
        # Hot-path query: "what active assignments does this user hold?"
        Index(
            "ix_scope_assignments_user_id_active",
            "user_id",
            "active",
            postgresql_where=text("ended_at IS NULL"),
        ),
        # Hot-path query: "who currently holds assignments under this tenant?"
        Index(
            "ix_scope_assignments_tenant_id_active",
            "tenant_id",
            "active",
            postgresql_where=text("ended_at IS NULL"),
        ),
        # Composite for "is this user currently assigned to this (tenant, domain, role)?"
        Index(
            "ix_scope_assignments_user_tenant_domain_role_active",
            "user_id",
            "tenant_id",
            "domain_id",
            "role",
            postgresql_where=text("ended_at IS NULL"),
        ),
        {
            "comment": (
                "Step 24.5b -- first-class scope assignments. Source of truth "
                "for role within (tenant, domain). Promotion/demotion/departure "
                "via end-and-recreate, never UPDATE in place. Mandatory key "
                "rotation wired at ScopeAssignmentService layer."
            )
        },
    )

    def __repr__(self) -> str:  # pragma: no cover -- debug only
        state = "active" if self.ended_at is None else f"ended={self.ended_reason}"
        return (
            f"<ScopeAssignment id={self.id} user={self.user_id} "
            f"tenant={self.tenant_id} domain={self.domain_id} "
            f"role={self.role!r} {state}>"
        )