"""User model -- durable person identity across tenants/agents.

Step 24.5b introduces the User layer. A User is the durable person; an Agent
is a person-in-a-role within a (tenant, domain) scope. One User can have many
Agents across tenants (e.g. Sarah at REMAX Crossroads + Sarah at a second
brokerage = one User, two Agent rows).

Design contract:
- Users are tenant-agnostic. No tenant_id column. Cross-tenant reads are
  platform-admin only, enforced at the service/policy layer (not here).
- Email is the natural lookup key. Case-insensitive uniqueness enforced via
  expression index in the migration (LOWER(email)) -- avoids citext extension
  dependency.
- Synthetic emails (agent-<id>@<tenant>.luciel.local) are allowed for the
  Step 23 Option B onboarding backward-compat path; flagged via `synthetic`
  bool so PIPEDA access/erasure flows can distinguish real users.
- Soft-delete via `active` per Invariant 3. Never hard-delete -- audit chain
  must remain walkable backwards from any historical Agent/MemoryItem.
- created_at / updated_at are timezone-aware UTC per project convention.
- PK is UUID (not the project's typical INTEGER) by deliberate choice -- Users
  are tenant-agnostic, so sequential-ID enumeration would leak cross-tenant
  identity counts. UUID also makes future federation (Step 38 tenant-merge,
  multi-region) cleaner.

Relationships:
- User 1..N Agent (one User, many person-role bindings across tenants/domains).
  Back-populated via Agent.user_id FK landed in File 1.3.
- User 1..N ScopeAssignment (Q6 resolution: scope assignments are first-class,
  Agent rows derived from active assignments). Back-populated via File 1.2.
- User 1..N MemoryItem (durable identity for memory attribution across role
  changes). Relationship deferred to Commit 2 (File 2.7 adds MemoryItem.user_id
  FK; relationship declaration lands alongside it to satisfy mapper resolution).

Migration:
- Schema lands in alembic revision <new>_add_users_scope_assignments_and_agent_user_id_fk
  (File 1.9). Hand-written per Invariant 12 -- pgvector/JSONB-adjacent tables
  are never autogenerated. Migration also creates pgcrypto extension if absent
  (for gen_random_uuid()).
"""
from __future__ import annotations

import uuid
from datetime import datetime, timezone
from typing import TYPE_CHECKING

from sqlalchemy import Boolean, DateTime, String, text
from sqlalchemy.dialects.postgresql import UUID as PG_UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import Base

if TYPE_CHECKING:
    from app.models.agent import Agent
    from app.models.memory import MemoryItem
    from app.models.scope_assignment import ScopeAssignment


class User(Base):
    """Durable person identity. Spans tenants. Soft-delete via active."""

    __tablename__ = "users"

    id: Mapped[uuid.UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    )

    # Natural lookup key. Case-insensitive uniqueness enforced via expression
    # index on LOWER(email) in the migration (File 1.9). Length cap matches
    # RFC 5321 maximum (320) with margin for synthetic suffixes.
    email: Mapped[str] = mapped_column(
        String(320),
        unique=True,
        nullable=False,
        index=True,
    )

    display_name: Mapped[str] = mapped_column(
        String(200),
        nullable=False,
    )

    # Synthetic-email flag. True for users auto-created via Option B onboarding
    # backward-compat path (Commit 2 OnboardingService change). Real users
    # created via POST /api/v1/users land with synthetic=False. PIPEDA
    # access/erasure paths filter on this.
    synthetic: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        server_default=text("false"),
    )

    # Invariant 3: soft-delete only. Cascade to ScopeAssignments + Agents +
    # ApiKeys handled in service layer (Commit 2: UserService.deactivate_user)
    # within the same txn (Invariant 4).
    active: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        server_default=text("true"),
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(timezone.utc),
        server_default=text("now()"),
    )

    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(timezone.utc),
        onupdate=lambda: datetime.now(timezone.utc),
        server_default=text("now()"),
    )

    # ------ relationships ------
    # Lazy="select" (default) -- explicit eager loading happens at the
    # repository layer where it's needed. Avoid N+1 silently.
    agents: Mapped[list["Agent"]] = relationship(
        "Agent",
        back_populates="user",
        foreign_keys="Agent.user_id",
        lazy="select",
    )

    scope_assignments: Mapped[list["ScopeAssignment"]] = relationship(
        "ScopeAssignment",
        back_populates="user",
        foreign_keys="ScopeAssignment.user_id",
        lazy="select",
    )

    # Step 24.5b File 2.8 -- restored from Commit 1 deferral.
    #
    # Original deferral (D8): the back-populates target
    # MemoryItem.actor_user_id column didn't land until Commit 2's
    # File 2.6a, so declaring this relationship in Commit 1 would
    # have crashed configure_mappers on first ORM use.
    #
    # Now safe: File 2.6a added MemoryItem.actor_user_id, File 2.7
    # landed it in DB schema, File 2.8 (this edit + the matching
    # MemoryItem.actor_user edit) closes the bidirectional pair.
    #
    # Used by Pillar 12 in Commit 3 to assert "all memory rows
    # attributable to this User across role changes" reads
    # correctly via user.memory_items.
    memory_items: Mapped[list["MemoryItem"]] = relationship(
        "MemoryItem",
        back_populates="actor_user",
        foreign_keys="MemoryItem.actor_user_id",
        lazy="select",
    )

    def __repr__(self) -> str:  # pragma: no cover -- debug only
        return (
            f"<User id={self.id} email={self.email!r} "
            f"synthetic={self.synthetic} active={self.active}>"
        )