"""UserInvite model -- first-class invite lifecycle for Team and Company tiers.

Step 30a.4 lands the invite-teammate primitive that Step 30a.4's `/app/team`
UI and Step 30a.5's `/app/company` UI both call. Previously the invite path
overloaded `/admin/luciel-instances` POST (Step 30a.1 commit G's
`teammate_email` field), which both (a) mis-used the daily-login magic-link
token class for what is structurally a set_password event for the invitee
and (b) had no first-class row to hang invite state on (pending, accepted,
expired, revoked). Step 30a.4 carves this surface out cleanly.

Design contract
---------------

A UserInvite is the durable record of "tenant T invited <email> to hold
role R within (tenant T, domain D) at time A; token has jti J; expires at
time B; status is pending|accepted|expired|revoked". The corresponding JWT
is a thin capability handle keyed by `token_jti`; the structured payload
(tenant_id, domain_id, role, inviter) lives here, not on the token.

* **Token is 24h-TTL via `mint_set_password_token(purpose="invite")`.**
  The set_password-class token (Step 30a.3 primitive) carries `sub`,
  `email`, `tenant_id`, `typ`, `purpose=invite`, `jti`. It does NOT carry
  `domain_id` or `role` -- those live here, looked up at redemption time
  by `token_jti`. This keeps Step 30a.3's auth surface untouched.

* **Invite row TTL is 7 days via `expires_at`** (independent of token TTL).
  If the 24h token lapses before the 7-day invite window, the resend
  affordance on `/app/team` rotates `token_jti` and re-mints a fresh
  token against the same invite row. This is closure-shape α (invite
  row is the source of truth on expiry) locked at Step 30a.4 plan-form.

* **Status is single-use.** Once redeemed (status='accepted'), the row
  is terminal; re-using the JWT against the redemption route returns 401.
  Replay prevention is the (`status='pending'` AND `expires_at > now()`)
  gate on redemption.

* **One pending invite per (tenant, lower(email))** -- partial unique
  index in the migration. Re-inviting after a revoke or expiry is fine
  (those rows are no longer 'pending'). A second pending invite for the
  same teammate under the same tenant is a UX bug we'd rather block at
  the schema layer than discover in production.

Relationships
-------------

* UserInvite N..1 TenantConfig (the inviting tenant).
* UserInvite N..1 User (the inviter -- the cookied user who clicked
  Invite teammate).
* UserInvite N..1 User (accepted_user -- the User row created or fetched
  on redemption). Nullable while status='pending'.
* `domain_id` is service-layer validated against domain_configs, NOT a
  direct FK -- domain_configs uses (tenant_id, domain_id) as its natural
  key, and the project convention (Agent, ScopeAssignment) is to validate
  composite-key references at the service layer rather than via composite
  FK. Same pattern as Agent.domain_id and ScopeAssignment.domain_id.

Invariants honored
------------------

* Invariant 3 (soft-delete only): no row is ever DELETEd. A revoked invite
  is `status='revoked'` with `revoked_at` stamped; an expired invite is
  `status='expired'` (flipped by the redemption gate or by the retention
  worker on its next scan; both shapes leave the row in place).
* Invariant 4 (audit-in-same-txn): create, redeem, revoke each emit an
  AdminAuditLog row in the same DB transaction as the row write. Wired at
  the InviteService layer.
* Invariant 12 (hand-written migration): the new `user_invites` table is
  created via a hand-written Alembic revision descending from the Step
  30a.3 head `a3c1f08b9d42`, not autogenerated.

Cross-refs
----------

CANONICAL_RECAP section 12 Step 30a.4 row (the design home).
ARCHITECTURE section 3.2.13 "Team-invite path" paragraph (the
implementation home, sharpened 2026-05-17 in the Step 30a.4 closing
commit to name this table and the four-event audit arc).
DRIFTS section 3 `~~D-team-self-serve-incomplete-invite-ui-missing-2026-05-16~~`
(the parent drift closed by the Step 30a.4 closing commit) and
`D-step-30a-4-live-300-paid-evidence-pending-intro-fee-scaling-2026-05-17`
(the carve-out drift carrying the live-$300 wire leg forward to the
very-end Stripe-Prices sweep).
"""
from __future__ import annotations

import enum
import uuid
from datetime import datetime
from typing import TYPE_CHECKING

from sqlalchemy import (
    DateTime,
    Enum as SAEnum,
    ForeignKey,
    Index,
    String,
    text,
)
from sqlalchemy.dialects.postgresql import UUID as PG_UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import Base, TimestampMixin

if TYPE_CHECKING:
    from app.models.user import User


class InviteStatus(str, enum.Enum):
    """Lifecycle state of a user invite. Stored on user_invites.status."""

    PENDING = "pending"
    ACCEPTED = "accepted"
    EXPIRED = "expired"
    REVOKED = "revoked"


class UserInvite(Base, TimestampMixin):
    """A pending or terminal invite for an email under (tenant, domain, role).

    Step 30a.4 first-class invite row. See module docstring for the design
    contract and the closure-shape (α) rationale.
    """

    __tablename__ = "user_invites"

    # PG UUID PK matching the User table convention. Sequential INTEGERs
    # would leak per-tenant invite counts via enumeration.
    id: Mapped[uuid.UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    )

    # The inviting tenant. RESTRICT mirrors User / ScopeAssignment / Agent
    # convention -- a tenant cannot be hard-deleted while invites reference
    # it; soft-deactivation goes through the AdminService cascade which
    # is responsible for revoking any pending invites in the same txn.
    tenant_id: Mapped[str] = mapped_column(
        String(100),
        ForeignKey("tenant_configs.tenant_id", ondelete="RESTRICT"),
        nullable=False,
        index=True,
    )

    # Service-layer validated against domain_configs(tenant_id, domain_id).
    # Mirrors Agent.domain_id and ScopeAssignment.domain_id -- no direct FK
    # because domain_configs uses a composite natural key. NOT NULL because
    # every invite resolves to a specific domain at provisioning time (for
    # Team tier this is the tenant's default domain; for Company tier the
    # inviter picks the domain explicitly).
    domain_id: Mapped[str] = mapped_column(
        String(100),
        nullable=False,
    )

    # The cookied user who clicked Invite teammate. RESTRICT mirrors the
    # User-as-actor convention elsewhere (Agent.user_id, ScopeAssignment.user_id).
    inviter_user_id: Mapped[uuid.UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="RESTRICT"),
        nullable=False,
        index=True,
    )

    # Email of the invitee. Stored as the raw form the inviter typed; the
    # partial-unique index on LOWER(invited_email) handles case-insensitive
    # dedupe. Length matches User.email (RFC 5321 max 320 + headroom).
    invited_email: Mapped[str] = mapped_column(
        String(320),
        nullable=False,
    )

    # Role label within the (tenant, domain) scope. Free-form for v1,
    # mirroring ScopeAssignment.role. Step 30a.4's Team tier defaults to
    # "teammate"; Step 30a.5's Company tier uses "department_lead" for the
    # Company-admin-invites-lead leg and "teammate" for the
    # lead-invites-agents leg.
    role: Mapped[str] = mapped_column(
        String(100),
        nullable=False,
        server_default=text("'teammate'"),
    )

    # JWT jti of the currently-outstanding token for this invite. Unique
    # so that redemption is O(1) by jti lookup and so that a leaked token
    # cannot collide with a different invite. Rotated by resend_invite.
    token_jti: Mapped[str] = mapped_column(
        String(64),
        nullable=False,
        unique=True,
        index=True,
    )

    # Lifecycle state. Native Postgres enum for portability of the values
    # into psql / DataGrip queries; matches the EndReason precedent on
    # ScopeAssignment.
    status: Mapped[InviteStatus] = mapped_column(
        SAEnum(
            InviteStatus,
            name="user_invite_status",
            native_enum=True,
            create_constraint=True,
            validate_strings=True,
            values_callable=lambda enum_cls: [m.value for m in enum_cls],
        ),
        nullable=False,
        server_default=text("'pending'"),
        index=True,
    )

    # When the invite row expires (7 days from creation by default; the
    # service layer is responsible for computing this from `created_at +
    # 7 days` at insert time so it survives token rotation cleanly).
    expires_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
    )

    # Stamped on redemption. NULL while status='pending'. Read by the
    # admin UI's "Accepted invites" list to surface "Jane accepted 3 days
    # ago" annotations.
    accepted_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )

    # The User row created (or fetched, in the rare case an existing User
    # is invited into a second tenant) at redemption time. NULL while
    # status='pending'. RESTRICT so an accepted-invite row can never be
    # orphaned from the User it provisioned.
    accepted_user_id: Mapped[uuid.UUID | None] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="RESTRICT"),
        nullable=True,
        index=True,
    )

    # Stamped on revoke. NULL while status='pending' or 'accepted'.
    revoked_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )

    # Which actor API key issued the revoke. SET NULL on api_keys hard-
    # delete (which we never do today but the FK shape matches the
    # ScopeAssignment.ended_by_api_key_id precedent). NULL for system-
    # initiated revokes (cascade from tenant deactivation).
    revoked_by_api_key_id: Mapped[int | None] = mapped_column(
        ForeignKey("api_keys.id", ondelete="SET NULL"),
        nullable=True,
    )

    # ------ relationships ------
    # Lazy="select" (default) -- explicit eager loading happens at the
    # repository layer where it is needed. Avoid N+1 silently.
    inviter: Mapped["User"] = relationship(
        "User",
        foreign_keys=[inviter_user_id],
        lazy="select",
    )

    accepted_user: Mapped["User | None"] = relationship(
        "User",
        foreign_keys=[accepted_user_id],
        lazy="select",
    )

    # ------ table-level indexes / constraints ------
    __table_args__ = (
        # Hot-path query: list pending invites under a tenant for the
        # admin UI. Partial index keeps the index small (only pending
        # rows are queried this way; accepted/expired/revoked rows are
        # browsed via the broader (tenant_id, status) composite).
        Index(
            "ix_user_invites_tenant_status_pending",
            "tenant_id",
            "status",
            postgresql_where=text("status = 'pending'"),
        ),
        # Case-insensitive lookup of "is there a pending invite for this
        # email under this tenant?" -- backs the duplicate-pending guard
        # in InviteService.create_invite and the partial unique below.
        Index(
            "ix_user_invites_invited_email_lower",
            text("LOWER(invited_email)"),
        ),
        # The duplicate-pending guard at the schema layer. Two terminal
        # rows (one revoked, one expired) for the same (tenant, email)
        # pair are fine -- this only blocks a second 'pending' row from
        # landing while a first one is still outstanding. Matches the
        # service-layer 409 the route surfaces on the same condition.
        Index(
            "uq_user_invites_tenant_email_pending",
            "tenant_id",
            text("LOWER(invited_email)"),
            unique=True,
            postgresql_where=text("status = 'pending'"),
        ),
        {
            "comment": (
                "Step 30a.4 -- first-class invite lifecycle. Token is a "
                "thin capability handle; this row is the structured "
                "payload. Closure-shape (alpha): invite row is source "
                "of truth on expiry (7 days); token TTL stays 24h with "
                "resend rotation."
            )
        },
    )

    def __repr__(self) -> str:  # pragma: no cover -- debug only
        return (
            f"<UserInvite id={self.id} tenant={self.tenant_id} "
            f"email={self.invited_email!r} role={self.role!r} "
            f"status={self.status.value}>"
        )
